### ISSUE TITLE
Jenkinsfile for Prisma scan doesn't publish results on failed scans

### ISSUE THREAD

**Issue by gbrandyburg** [utd-prisma-cloud1/ubuntu#2]
Need to use a try / finally block (example from self-hosted env is below), otherwise the publish call is skipped.

stage('Scan Image and Publish to Jenkins') {
        try {
            prismaCloudScanImage ca: '', cert: '', dockerAddress: 'unix:///var/run/docker.sock', ignoreImageBuildTime: true, image: "tl_demo/struts2_demo:${env.struts2_version}_build", key: '', logLevel: 'debug', podmanPath: '', project: '', resultsFile: 'prisma-cloud-scan-results.json'
        } finally {
            prismaCloudPublish resultsFilePattern: 'prisma-cloud-scan-results.json'
        }
    }

**Comment by utd-prisma-cloud1** [comment]
I've update the code.
